-- AlterTable
ALTER TABLE `Persona` MODIFY `motto` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `level` INTEGER NOT NULL DEFAULT 0,
    MODIFY `boost` INTEGER NOT NULL DEFAULT 500,
    MODIFY `cash` INTEGER NOT NULL DEFAULT 200000,
    MODIFY `rating` INTEGER NOT NULL DEFAULT 0,
    MODIFY `rep` INTEGER NOT NULL DEFAULT 0,
    MODIFY `score` INTEGER NOT NULL DEFAULT 0,
    MODIFY `levelPercentage` INTEGER NOT NULL DEFAULT 0,
    MODIFY `repLevel` INTEGER NOT NULL DEFAULT 0;
