version: '3.7'
services:
  nodejs:
    image: node:14
    volumes:
      - ".:/app"
    working_dir: "/app"
    depends_on:
      - db
    ports:
      - "5222:5222"
      - "1337:1337"
      - "5555:5555"
    command: 'yarn dev'
  db:
    image: "mysql/mysql-server:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "zeus"
      MYSQL_PASSWORD: "zeus"
      MYSQL_DATABASE: "zeus"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./.docker/config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./.docker/storage/mysql:/var/lib/mysql"